version: '3'

services:
    addd:
        build:
            context: .
            args:
                http_proxy: ${http_proxy}
                https_proxy: ${https_proxy}
                no_proxy: ${no_proxy}
        image: redsux/addd
        container_name: addd
        restart: always
        ports:
        - "53:53/udp"
        - "1632:1632/tcp"
        - "10001:10001/udp"
        - "10001:10001/tcp"
        - "10002:10002/tcp"
        command: -domain local.
        #command: -domain local. -level debug -ha_bind ${HOSTIP}
        #volumes:
        #- "/path/to/db/file.db:/addd.db"
